config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  resources :tasks, except: [:new]
  resources :subtaskings
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subtasking.rb
class Subtasking < ApplicationRecord
  belongs_to :subtask, class_name: "Task"
  belongs_to :supertask, class_name: "Task"

  accepts_nested_attributes_for :subtask, :supertask
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :subtask_subtaskings, foreign_key: :supertask_id, class_name: "Subtasking", dependent: :destroy
  has_many :subtasks, through: :subtask_subtaskings

  has_many :supertask_subtaskings, foreign_key: :subtask_id, class_name: "Subtasking", dependent: :destroy
  has_many :supertasks, through: :supertask_subtaskings

  accepts_nested_attributes_for :subtask_subtaskings, :supertask_subtaskings

  def build_sub_and_super_subtaskings
    [self.subtask_subtaskings, self.supertask_subtaskings].each { |foo| foo.build }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/subtaskings_controller.rb
class SubtaskingsController < ApplicationController
  before_action :set_subtasking, only: %i[ show edit update destroy ]

  # GET /subtaskings or /subtaskings.json
  def index
    @subtaskings = Subtasking.all
  end

  # GET /subtaskings/1 or /subtaskings/1.json
  def show
  end

  # GET /subtaskings/new
  def new
    @subtasking = Subtasking.new
    @tasks = Task.all
  end

  # GET /subtaskings/1/edit
  def edit
  end

  # POST /subtaskings or /subtaskings.json
  def create
    @subtasking = Subtasking.new(subtasking_params)

    respond_to do |format|
      if @subtasking.save
        format.html { redirect_back(fallback_location: root_path, notice: "Subtasking was successfully created") }
        format.json { render :show, status: :created, location: @subtasking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subtasking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subtaskings/1 or /subtaskings/1.json
  def update
    respond_to do |format|
      if @subtasking.update(subtasking_params)
        format.html { redirect_to @subtasking, notice: "Subtasking was successfully updated." }
        format.json { render :show, status: :ok, location: @subtasking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subtasking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subtaskings/1 or /subtaskings/1.json
  def destroy
    @subtasking.destroy
    respond_to do |format|
      format.html { redirect_to subtaskings_url, notice: "Subtasking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subtasking
      @subtasking = Subtasking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subtasking_params
      params.require(:subtasking).permit(:supertask_id, :subtask_id, subtask_attributes: [:title, :description])
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all.select { |task| [task, task.title, task.description].all? }
    @new_task = Task.new

    # Build associations for forms.
    @tasks.each(&:build_sub_and_super_subtaskings)
  end

  # GET /tasks/1 or /tasks/1.json
  def show
    @tasks = Task.all
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_url, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :description, subtask_subtaskings_attributes: [:subtask_id, :supertask_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subtaskings_helper.rb
module SubtaskingsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.erb
<header>
  <nav class="nav">
    <ul>
      <%= link_to "All Tasks", tasks_path %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Galileo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/subtaskings/_form.html.erb
<%= form_with(model: subtasking) do |form| %>
  <% if subtasking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subtasking.errors.count, "error") %> prohibited this subtasking from being saved:</h2>

      <ul>
        <% subtasking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= form.label "subtasking", 'Supertask:' %>
  <%= select("subtasking", "supertask_id", Task.all.collect {|t| [t.title, t.id] } ) %>

  <%= form.label "subtasking", 'Subtask:' %>
  <%= select("subtasking", "subtask_id", Task.all.collect {|t| [t.title, t.id] } ) %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subtaskings/edit.html.erb
<h1>Editing Subtasking</h1>

<%= render 'form', subtasking: @subtasking %>

<%= link_to 'Show', @subtasking %> |
<%= link_to 'Back', subtaskings_path %>

app/views/subtaskings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subtaskings</h1>

<% if Subtasking.none? %>

  <p>Currently no subtaskings</p>

<% else %>

  <table>
    <thead>
      <tr>
        <th>Supertask</th>
        <th>Subtask</th>
      </tr>
    </thead>

    <tbody>
      <% @subtaskings.each do |subtasking| %>
        <tr>
          <td><%= subtasking.supertask.title %></td>
          <td><%= subtasking.subtask.title %></td>
          <td><%= link_to 'Show', subtasking %></td>
          <td><%= link_to 'Edit', edit_subtasking_path(subtasking) %></td>
          <td><%= link_to 'Destroy', subtasking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>

<br>

<%= link_to 'New Subtasking', new_subtasking_path %>

app/views/subtaskings/new.html.erb
<h1>New Subtasking</h1>

<%= render 'form', subtasking: @subtasking %>

<%= link_to 'Back', subtaskings_path %>

app/views/subtaskings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_subtasking_path(@subtasking) %> |
<%= link_to 'Back', subtaskings_path %>

app/views/tasks/_form.html.erb
<%= form_with(model: task, class: 'new-task-form') do |form| %>
<% if task.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

  <ul>
    <% task.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= form.label :title, 'Title:' %>
<%= form.text_field :title %>

<%= form.label :description, 'Description:' %>
<%= form.text_field :description %>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/tasks/_subtask_form.html.erb
<%= form_with model: subtasking, html: html_options do |form| %>
<h6 class="card__form__title">Add a new sub-task</h6>
<%= form.hidden_field :supertask_id %>

<%= form.fields_for :subtask, subtasking.build_subtask do |t| %>

<% [
  {property: :title, text: 'Title'},
  {property: :description, text: 'Description'}
  ].each do |hash| %>

<div class="card__form__fieldset">
  <%= t.label hash[:property], hash[:text], class: 'card__form__label' %>
  <%= t.text_field hash[:property], class: 'card__form__field' %>
</div>
<% end %>

<% end %>

<%= form.submit %>
<% end %>

app/views/tasks/_subtasks_and_supertasks.html.erb
<% if @task.subtasks.any? %>
  <h5>Subtasks</h5>
  <ul>
    <% @task.subtasks.each do |subtask| %>
      <li><%= link_to subtask.title, task_path(subtask) %></li>
    <% end %>
  </ul>
<% end %>

<h5>Add a new Subtask!</h5>
<%= form_with model: Subtasking.new do |form| %>
  <%= hidden_field_tag 'subtasking[supertask_id]', @task.id %>
  <%= form.label 'subtasking', 'Subtask:' %>
  <%= select("subtasking", "subtask_id", @tasks.collect {|t| [t.title, t.id] } ) %>
  <%= form.submit %>
<% end %>

<% if @task.supertasks.any? %>
  <h5>Supertasks</h5>
  <ul>
    <% @task.supertasks.each do |supertask| %>
      <li><%= link_to supertask.title, task_path(supertask) %></li>
    <% end %>
  </ul>
<% end %>
<h5>Add a new Supertask</h5>
<%= form_with model: Subtasking.new do |form| %>
  <%= hidden_field_tag 'subtasking[subtask_id]', @task.id %>
  <%= form.label 'subtasking', 'Supertask:' %>
  <%= select("subtasking", "supertask_id", @tasks.collect {|t| [t.title, t.id] } ) %>
  <%= form.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class="tasks-index">
  <h1 class="tasks-index__title">All tasks</h1>

  <section class="tasks-index__list">
    <% @tasks.each do |task| %>
    <div class='card'>

      <h5 class="card__title">
        <%= task.title %>
      </h5>

      <p class="card__description">
        <%= task.description %>
      </p>

      <div class="card__links">
        <%= link_to "View Task", task %>
        <%= link_to 'Edit', edit_task_path(task) %>
        <%= link_to 'Destroy', task, method: :delete %>
      </div>

      <%= render partial: 'subtask_form', locals: { 
        subtasking: task.subtask_subtaskings.first,
        html_options: {class: 'card__form'}}
        %>

    </div>
    <% end %>
  </section>
  <br>
  <%= render "form", task: @new_task %>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>
<h2><%= @task.title %></h2>
<h5><%= @task.description %></h5>

<%= render 'subtasks_and_supertasks' %>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>